name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Start services
        run: docker compose -f compose/spine-only.yml up -d

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run pytest

      - name: Shutdown services
        if: always()
        run: docker compose -f compose/spine-only.yml down
