name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [spine-only, full]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pipx install poetry

      - name: Lock dependencies
        run: poetry lock

      - name: Install dependencies
        run: poetry install

      - name: Build image
        run: docker build -t stage0-api .

      - name: Start services
        run: docker compose -f compose/${{ matrix.profile }}.yml up -d

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run pytest

      - name: Locust smoke test
        run: poetry run locust -f tests/locustfile.py --headless -u 1 -r 1 -t 10s

      - name: Shutdown services
        if: always()
        run: docker compose -f compose/${{ matrix.profile }}.yml down
