name: E2E

on:
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
        working-directory: e2e
      - name: Start stack
        run: docker compose -f compose/full.yml up -d
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
      - name: Stop stack
        if: always()
        run: docker compose -f compose/full.yml down
